name: Documentation

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.7'
      - run: >
          sudo apt-get install --no-install-recommends gfortran python3-setuptools python3-wheel
          && pip3 install numpy && pip3 install Cython && pip3 install classy
          && pip3 install matplotlib && julia --project=docs/ -e 'using Pkg; Pkg.add(url = "https://github.com/marcobonici/CosmoCentral.jl"); Pkg.instantiate()'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --project=docs/ docs/make.jl
